server:
  port: 8085

spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/librarymsdb?ApplicationName=LMS&currentSchema=rest
    username: libraryms
    password: libraryms
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 600
  refreshTokenExpiration: 86400
  route:
    authentication:
      path: auth
      logout: logout
      refresh: refresh
      forgetPassword: forgetPassword
      changePassword: changePassword