server:
  port: 8087

spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/librarymsdb?ApplicationName=LMS&currentSchema=mail
    username: libraryms
    password: libraryms
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: libraryms
    password: libraryms

message-broker-queues:
  job-mail-create: job.mail.create
  job-mail-update: job.mail.update
  job-mail-delete: job.mail.delete
  job-mail-send: job.mail.send
