server:
  port: 8087

spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/librarymsdb?ApplicationName=LMS&currentSchema=mail
    username: libraryms
    password: libraryms
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: libraryms
    password: libraryms
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ca8b1567bb1e95
    password: b9ec1376b42646
    properties:
      mail:
        smtp:
          ssl:
            enable: false
          auth: true
          starttls:
            enable: true

message-broker-queues:
  job-mail-create: job.mail.create
  job-mail-update: job.mail.update
  job-mail-delete: job.mail.delete
  job-mail-send: job.mail.send

job-settings:
  mail-send-interval: 10000