package com.emincingoz.bookservice.model;

public enum unused {
    FANTASY, SCIENCE_FICTION, DYSTOPIAN, ACTION_ADVENTURE, MYSTERY, HORROR, THRILLER_SUSPENSE, HISTORICAL_FICTION, ROMANCE, WOMEN_FICTION, LGBTQ, CONTEMPORARY_FICTION, LITERARY_FICTION, MAGICAL_REALISM, GRAPHIC_NOVEL, SHORT_STORY, YOUNG_ADULT, NEW_ADULT, CHILDREN, NONFICTION, MEMOIR_AUTOBIOGRAPHY, BIOGRAPHY, FOOD_DRINK, ART_PHOTOGRAPHY, SELF_HELP, HISTORY, TRAVEL, TRUE_CRIME, HUMOR, ESSAYS, GUIDE_HOWTO, RELIGION_SPIRITUALITY, HUMANITIES_SOCIAL_SCIENCES, PARENTING_FAMILIES, SCIENCE_TECHNOLOGY,

    WORLD_CLASSICS, LOVE,
}
